######################################################
#                  AWARDS 8.0                        #
######################################################

templates:
  imdb:
    optional:
      - trakt_list
    sort_title: ZZZZZZ+<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    visible_library: true
    trakt_list:
      - <<trakt_list>>

  Award:
    smart_label: release.desc
    sync_mode: sync
    sort_title: ZZZZZZ+<<collection_name>>

  Award Other:
    smart_label: release.desc
    sync_mode: sync
    sort_title: ZZZZZZ+<<collection_name>>
    visible_library: true

# Movies who has won some the most prestigious awards
collections:
  BAFTA - Best Film:
    template: { name: imdb }
    summary: The British Academy Film Awards is an annual award show hosted by the British Academy of Film and Television Arts (BAFTA) to honour the best British and international contributions to film. The ceremonies were initially held at the flagship Odeon cinema in Leicester Square in London, before being held at the Royal Opera House.
    visible_shared: monthly(28)
    file_poster: config/posters/BAFTA Best Film.png
    imdb_search:
      event.winning: "bafta"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  BAFTA - Nominees:
    template: { name: imdb }
    summary: The British Academy Film Awards is an annual award show hosted by the British Academy of Film and Television Arts (BAFTA) to honour the best British and international contributions to film. The ceremonies were initially held at the flagship Odeon cinema in Leicester Square in London, before being held at the Royal Opera House.
    file_poster: config/posters/BAFTA Nominees.png
    imdb_search:
      event: "bafta"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Berlinale - Winners:
    template: { name: Award }
    summary: The Berlin International Film Festival, also known as Berlinale, is one of the largest and most prestigious film festivals in the world. It is held annually in Berlin, Germany, and showcases a diverse range of international films.
    file_poster: config/posters/Berlinale Winners.png
    letterboxd_list: https://letterboxd.com/koyoti/list/berlinale-golden-bear-winners/

  Cannes - Best Picture:
    template: { name: imdb }
    summary: The Cannes Film Festival until 2003 called the International Film Festival (Festival international du film) and known in English as the Cannes Film Festival, is an annual film festival held in Cannes, France, which previews new films of all genres, including documentaries, from all around the world. Founded in 1946, the invitation-only festival is held annually at the Palais des Festivals et des Congrès. The festival was formally accredited by the FIAPF in 1951.
    visible_shared: monthly(17)
    file_poster: config/posters/Cannes Best Picture.png
    imdb_search:
      event.winning: "cannes"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Critics Choice Awards - Nominees:
    template: { name: imdb }
    summary: The Critics' Choice Movie Awards (formerly known as the Broadcast Film Critics Association Award) is an awards show presented annually by the American-Canadian Critics Choice Association to honor the finest in cinematic achievement.
    file_poster: config/posters/Critics Choice Nominees.png
    imdb_search:
      event: "choice"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Critics Choice Awards - Winners:
    template: { name: imdb }
    summary: The Critics' Choice Movie Awards (formerly known as the Broadcast Film Critics Association Award) is an awards show presented annually by the American-Canadian Critics Choice Association to honor the finest in cinematic achievement.
    file_poster: config/posters/critics choice winners.png
    imdb_search:
      event.winning: "choice"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  European Film Award - Winners:
    template: { name: Award }
    summary: The European Film Awards (EFA) is an annual awards ceremony that honors outstanding achievements in European cinema. The awards were first presented in 1988, and since then, they have become one of the most prestigious film awards in the world.
    file_poster: config/posters/european film awards.png
    letterboxd_list: https://letterboxd.com/ra_pha/list/european-film-awards/

  Golden Globe - Best Picture:
    template: { name: Award }
    summary: The Golden Globe Awards are accolades bestowed by the Hollywood Foreign Press Association starting in January 1944, recognizing excellence in both American and international film and television. Beginning in 2022, there are 105 members of the HFPA.
    visible_shared:
      - monthly(23)
      - monthly(24)
    file_poster: config/posters/Golden Globe Best Picture.png
    trakt_list: https://trakt.tv/users/maxwelldeux/lists/golden-globe-award-best-motion-picture

  Golden Globe - Winners:
    template: { name: imdb }
    summary: The Golden Globe Awards are accolades bestowed by the Hollywood Foreign Press Association starting in January 1944, recognizing excellence in both American and international film and television. Beginning in 2022, there are 105 members of the HFPA.
    visible_shared:
      - monthly(17)
      - monthly(18)
    file_poster: config/posters/Golden Globe Winners.png
    imdb_search:
      event.winning: "golden"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Oscars - Best Picture:
    template: { name: Award Other }
    visible_shared:
      - monthly(21)
      - monthly(22)
    summary: Highest honor at the oscars.
    file_poster: config/posters/Oscars best pictures.png
    trakt_list: https://trakt.tv/users/thefork/lists/academy-awards-best-picture-winners?sort=rank,asc

  Oscars - Nominees:
    template: { name: imdb }
    file_poster: config/posters/Oscars Nominees.png
    summary: Oscar Category Winning Movies.
    imdb_search:
      event: "oscar"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Oscars - Winners:
    template: { name: imdb }
    visible_shared:
      - monthly(30)
      - monthly(31)
    file_poster: config/posters/Oscars award winners.png
    summary: Oscar Category Winning Movies.
    imdb_search:
      event.winning: "oscar"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Razzies - Worst Picture:
    template: { name: imdb }
    summary: Worst movies of the year award.
    file_poster: config/posters/Razzie worst pic.png
    imdb_search:
      event.winning: "razzie"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Sundance - Grand Jury:
    template: { name: Award }
    summary: The Sundance Film Festival (formerly Utah/US Film Festival, then US Film and Video Festival) is an annual film festival organized by the Sundance Institute. It is the largest independent film festival in the United States, with more than 46,660 attending in 2016.
    file_poster: config/posters/Sundance GRAND JURY.png
    trakt_list: https://trakt.tv/users/maxwelldeux/lists/sundance-film-festival-grand-jury-prize

  Sundance - Winners:
    template: { name: imdb }
    summary: A list of all (with exceptions of short movies) films that won awards at the American Sundance Film Festival.
    file_poster: config/posters/Sundance WINNERS.png
    imdb_search:
      event.winning: "sundance"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Venice - Best Picture:
    template: { name: Award }
    summary: The Venice Film Festival or Venice International Film Festival is an annual film festival held in Venice, Italy. It is the world's oldest film festival and one of the big six International film festivals worldwide, which include the Big Three European Film Festivals, alongside the Toronto Film Festival in Canada the Sundance Film Festival in the United States and the Melbourne International Film Festival in Australia.
    file_poster: config/posters/venice BEST PIC.png
    trakt_list: https://trakt.tv/users/maxwelldeux/lists/venice-film-festival-golden-lion?sort=rank,asc
