######################################################
#                SEPARATORS 3.0                      #
######################################################
templates:
  Separator:
    smart_label: random
    sync_mode: sync
    plex_search:
      all:
        title: breaking bad

collections:
  Award Collections:
    template: { name: Separator }
    sort_title: zzzzz_<<AAA
    summary: Award collections up next.
    file_poster: config/posters/Award Collections.png

  Chart Collections:
    template: { name: Separator }
    sort_title: ++++++_ZZZ
    summary: Chart collections up next.
    file_poster: config/posters/Chart Collections.png

  Decade Collections:
    template: { name: Separator }
    sort_title: zz_AAA
    summary: Decade collections up next.
    file_poster: config/posters/Decade Collections.png

  Franchise Collections:
    template: { name: Separator }
    sort_title: zzz_AAA
    summary: Franchise collections up next.
    file_poster: config/posters/Franchise Collections.png

  Genre Collections:
    template: { name: Separator }
    sort_title: +01_AAA
    summary: Genre collections up next.
    file_poster: config/posters/Genre Collections.png

  Network Collections:
    template: { name: Separator }
    sort_title: zzzzzz_<<
    summary: Network collections up next.
    file_poster: config/posters/Network Collections.png

  Rating Collections:
    template: { name: Separator }
    sort_title: zzzzzzz_11
    summary: Rating collections up next.
    file_poster: config/posters/Rating Collections.png

  Special Collections:
    template: { name: Separator }
    sort_title: ++++_000
    summary: Special collections up next.
    file_poster: config/posters/Special Collections.png

  Streaming Collections:
    template: { name: Separator }
    sort_title: ++_AAA
    summary: Streaming collections up next.
    file_poster: config/posters/Streaming Collections.png

  Subgenre Collections:
    template: { name: Separator }
    sort_title: +02_AAA
    summary: Subgenre collections up next.
    file_poster: config/posters/Subgenre Collections.png

  Year Collections:
    template: { name: Separator }
    sort_title: zzzz_AAA
    summary: Year collections up next.
    file_poster: config/posters/Year Collections.png
