#############################################################
#                       AWARDS 6.0                          #
#############################################################

templates:
  imdb:
    sort_title: "zzzzz_<<num>>_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=<<title_type>>&groups=<<groups>>&languages=<<languages>>&sort=release_date,desc
      limit: 350

  letterboxd:
    optional:
      - letterboxd_extra_1
      - letterboxd_extra_2
      - letterboxd_extra_3
      - letterboxd_extra_4
      - letterboxd_extra_5
    sort_title: "zzzzz_<<num>>_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    letterboxd_list::
      url: https://letterboxd.com/<<user>>/list/<<list>>/by/<<sort>>
      limit: 350

  custom_1:
    optional:
      - trakt_list
    sort_title: "zzzzz_<<num>>_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    imdb_list:
      url: https://www.imdb.com/list/<<imdb_list>>/?sort=release_date,desc
      limit: 350

  custom_2:
    optional:
      - trakt_list
    sort_title: "zzzzz_<<num>>_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    trakt_list:
      - <<trakt_list>>

# TV shows who has won some the most prestigious awards
collections:
  BAFTA - Winners:
    summary: "A collection of BAFTA Winners"
    visible_shared: monthly(10)
    file_poster: config/posters/BAFTA Winners.png
    template: { name: custom_1, imdb_list: "ls538625886" }

  Critics Choice Awards - Winners:
    summary: "A collection of Critics Choice Award Winners"
    visible_shared: monthly(5)
    file_poster: config/posters/critics choice winners.png
    template:
      {
        name: custom_2,
        trakt_list: "https://trakt.tv/users/fdamico/lists/critics-choice-series?sort=released,asc",
      }

  Emmy - Winners:
    summary: "A collection of Emmy Award Winners"
    visible_library: true
    visible_shared: monthly(20)
    file_poster: config/posters/Emmy Winners.png
    template:
      {
        name: custom_2,
        trakt_list: "https://trakt.tv/users/diimaan/lists/primetime-emmy-winners?sort=rank,asc",
      }

  Emmy - Nominees:
    summary: "A collection of Emmy Award Nominees"
    file_poster: config/posters/Emmy Nominees.png
    template:
      {
        name: custom_2,
        trakt_list: "https://trakt.tv/users/diimaan/lists/primetime-emmy-nominees?sort=rank,asc",
      }

  Golden Globe - Nominees:
    summary: "A collection of Golden Globes Nominees"
    file_poster: config/posters/Golden Globe Nominees.png
    template:
      {
        name: imdb,
        groups: "golden_globe_nominee",
        title_type: "tv_series,tv_special,tv_miniseries",
        languages: "en",
      }

  Golden Globe - Winners:
    summary: "A collection of Golden Globes Winners"
    visible_shared: monthly(15)
    file_poster: config/posters/Golden Globe Winners.png
    template:
      {
        name: imdb,
        groups: "golden_globe_winners",
        title_type: "tv_series,tv_special,tv_miniseries",
        languages: "en",
      }
