######################################################
#                   SPECIALS 14.0                    #
######################################################

templates:
  Rating:
    collection_order: custom
    sync_mode: sync

  Special:
    smart_label: random
    sync_mode: sync
    sort_title: +++_<<collection_name>>
    visible_library: true

  Special Smart:
    sync_mode: sync
    sort_title: ++++_<<collection_name>>
    visible_library: true

  Special Smart Other:
    sync_mode: sync
    sort_title: +++_<<collection_name>>
    visible_library: true

collections:
  18+:
    template: { name: Special Smart }
    visible_shared: monthly(9)
    summary: TV shows with this rating are generally not suitable for children or individuals under 17 (some sources may say 18). This content is only made for mature audiences because it contains mature themes, such as gore, sexual violence, strong language, nudity, substances, smoking, and sex.
    file_poster: config/posters/18+.png
    smart_filter:
      sort_by: random
      limit: 200
      validate: false
      all:
        content_rating: TV-MA

  480P+:
    template: { name: Special }
    summary: A collection of TV Shows in SD, 480p and 576p quality.
    sort_title: ++++_480P+
    file_poster: config/posters/480P+.png
    plex_search:
      any:
        resolution:
          - SD
          - 480p
          - 576p

  720P:
    template: { name: Special }
    summary: A collection of TV Shows in 720p quality.
    sort_title: ++++_720P
    file_poster: config/posters/720P.png
    plex_search:
      all:
        resolution: 720p

  1080P:
    template: { name: Special }
    summary: A collection of TV Shows in 1080p quality.
    sort_title: +++_1080P
    file_poster: config/posters/1080P.png
    plex_search:
      all:
        resolution: 1080p

  2160P:
    template: { name: Special }
    summary: A collection of TV Shows in 4K.
    sort_title: +++_2160P
    file_poster: config/posters/2160P.png
    plex_search:
      all:
        resolution: 4K

  DV/HDR:
    template: { name: Special }
    summary: A collection of TV Shows in HDR10+ and Dolby Vision.
    file_poster: config/posters/DVHDR.png
    plex_search:
      all:
        hdr: true

  Family Friendly:
    template: { name: Special }
    summary: Family Friendly recognizes outstanding entertainment with an official seal for quality and impact. Age Approved Selections include age-appropriate media with the potential to spark family conversations.
    file_poster: config/posters/Family Friendly.png
    visible_shared: monthly(10)
    trakt_list: https://trakt.tv/users/plexmetamanager/lists/common-sense-selection-shows?sort=rank,asc

  Longest:
    template: { name: Special }
    summary: The lengthiest shows on Plex.
    file_poster: config/posters/Longest.png
    trakt_list:
      - https://trakt.tv/users/belamarlua/lists/long-shows-i-watched-more-then-one-time?sort=rank,asc
      - https://trakt.tv/users/copeland1994/lists/all-time-series-rankings-long-running-shows-only?sort=rank,asc

  Newly Released:
    template: { name: Special Smart Other }
    file_poster: config/posters/Newly Released.png
    summary: Shows recently released in the past 2 months.
    visible_shared: monthly(27)
    smart_filter:
      sort_by: release.desc
      validate: false
      all:
        release: 61

  Popular:
    template: { name: Special }
    tautulli_popular:
      list_days: 31
      list_size: 50
      list_buffer: 20
      list_minimum: 1
    file_poster: config/posters/Popular.png
    summary: Most popular shows on Plex the past 2 months.

  Random:
    template: { name: Special Smart Other }
    file_poster: config/posters/Random.png
    summary: Random TV Shows.
    visible_shared: monthly(5)
    smart_filter:
      sort_by: random
      limit: 250
      validate: false
      all:
        audience_rating.gte: 4.0

  Watched:
    template: { name: Special }
    tautulli_watched:
      list_days: 9999
      list_size: 9999
      list_buffer: 20
      list_minimum: 1
    file_poster: config/posters/Watched.png
    summary: Shows watched on Plex by all users.
    smart_label: viewed.desc

  Worst:
    template: { name: Special Smart Other }
    summary: Worst shows on Plex rated 5.5 or lower.
    file_poster: config/posters/Worst.png
    smart_filter:
      sort_by: audience_rating.asc
      validate: false
      all:
        audience_rating.lte: 5.5

  #############################################################
  #                       RATINGS 1.0                         #
  #############################################################

  10/10:
    template: { name: Rating }
    summary: TV Shows with a user rating of 10/10 (sorted from best to worst).
    sort_title: zzzzzzzzzzz_10/10
    file_poster: config/posters/10.png
    trakt_list: https://trakt.tv/users/jhn322/lists/10-10-tv-shows?sort=rank,asc

  9/10:
    template: { name: Rating }
    summary: TV Shows with a user rating of 9/10 (sorted from best to worst).
    sort_title: zzzzzzzzzz_9/10
    file_poster: config/posters/9.png
    trakt_list: https://trakt.tv/users/jhn322/lists/9-10-tv-shows?sort=rank,asc

  8/10:
    template: { name: Rating }
    summary: TV Shows with a user rating of 8/10 (sorted from best to worst).
    sort_title: zzzzzzzzz_8/10
    file_poster: config/posters/8.png
    trakt_list: https://trakt.tv/users/jhn322/lists/8-10-tv-shows?sort=rank,asc

  7/10:
    template: { name: Rating }
    summary: TV Shows with a user rating of 7/10 (sorted from best to worst).
    sort_title: zzzzzzzz_7/10
    file_poster: config/posters/7.png
    trakt_list: https://trakt.tv/users/jhn322/lists/7-10-tv-shows?sort=rank,asc

  6/10:
    template: { name: Rating }
    summary: TV Shows with a user rating of 6/10 (sorted from best to worst).
    sort_title: zzzzzzz_6/10
    file_poster: config/posters/6.png
    trakt_list: https://trakt.tv/users/jhn322/lists/6-10-tv-shows?sort=rank,asc
